# -*- coding: utf-8 -*-
"""wdbc_classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o1UOHZjEnyXlwquY81YvF6AUTJic8iGQ

# WDBC Binary Classification Project
Using scikit-learn to classify breast cancer tumors as malignant or benign.

## Step 2: Load the Dataset
"""

from sklearn import datasets, svm, tree, neighbors, ensemble, metrics
import matplotlib.pyplot as plt
import numpy as np

wdbc = datasets.load_breast_cancer()
X = wdbc.data
y = wdbc.target

print("Data shape:", X.shape)
print("Target shape:", y.shape)
print("Target names:", wdbc.target_names)
print("First 5 feature names:", wdbc.feature_names[:5])

"""## Step 3: Train the Default SVM Classifier
Calculate accuracy, precision, and recall.
"""

model = svm.SVC()
model.fit(X, y)
predict = model.predict(X)

print("Default SVM Metrics:")
print("Accuracy:", round(metrics.accuracy_score(y, predict), 4))
print("Precision:", round(metrics.precision_score(y, predict), 4))
print("Recall:", round(metrics.recall_score(y, predict), 4))

"""## Step 4: Compare Multiple Classifiers"""

models = {
    "SVM": svm.SVC(),
    "Decision Tree": tree.DecisionTreeClassifier(random_state=42),
    "KNN": neighbors.KNeighborsClassifier(),
    "Random Forest": ensemble.RandomForestClassifier(random_state=42)
}

results = {}
for name, clf in models.items():
    clf.fit(X, y)
    pred = clf.predict(X)
    acc = metrics.accuracy_score(y, pred)
    results[name] = acc
    print(f"{name} Accuracy: {acc:.4f}")

"""## Step 5: Find the Best Classifier"""

best_name = max(results, key=results.get)
print(f"Best Classifier: {best_name} (Accuracy: {results[best_name]:.4f})")

"""## Step 6: Confusion Matrix"""

best_model = models[best_name]
best_pred = best_model.predict(X)
cm = metrics.confusion_matrix(y, best_pred)

disp = metrics.ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=wdbc.target_names)
fig, ax = plt.subplots(figsize=(7, 5))
disp.plot(ax=ax, colorbar=False, cmap="Blues")
ax.set_title(f"Confusion Matrix - {best_name}")
plt.tight_layout()
plt.savefig("wdbc_classification_matrix.png", dpi=150)
plt.show()
print("Saved: wdbc_classification_matrix.png")

"""## Step 7: Scatter Plot"""

cmap = np.array([
    (1, 0, 0),   # Red for malignant
    (0, 0, 1)    # Blue for benign
])

x_feature = 0
y_feature = 2

plt.figure(figsize=(8, 6))

plt.title("WDBC Classification - " + wdbc.feature_names[x_feature] + " vs " + wdbc.feature_names[y_feature])

plt.scatter(
    X[:, x_feature],
    X[:, y_feature],
    c=cmap[y],
    edgecolors=cmap[predict]
)

plt.xlabel(wdbc.feature_names[x_feature])
plt.ylabel(wdbc.feature_names[y_feature])

plt.tight_layout()
plt.savefig("wdbc_classification_scatter.png", dpi=150)
plt.show()
print("Saved: wdbc_classification_scatter.png")
